-- MySQL Script generated by MySQL Workbench
-- Fri Sep 23 14:17:31 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema houses
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema houses
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `houses` DEFAULT CHARACTER SET utf8mb3 ;
USE `houses` ;

-- -----------------------------------------------------
-- Table `houses`.`information`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `houses`.`information` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(450) NULL DEFAULT NULL,
  `link` VARCHAR(450) NULL DEFAULT NULL,
  `description` VARCHAR(450) NULL DEFAULT NULL,
  `surface` VARCHAR(450) NULL DEFAULT NULL,
  `image` VARCHAR(450) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 8775
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `houses`.`price`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `houses`.`price` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `price` DOUBLE NULL DEFAULT NULL,
  `date` DATETIME NULL DEFAULT NULL,
  `link` VARCHAR(450) NULL DEFAULT NULL,
  `title` VARCHAR(450) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 5258
DEFAULT CHARACTER SET = utf8mb3;

USE `houses` ;

-- -----------------------------------------------------
-- Placeholder table for view `houses`.`houses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `houses`.`houses` (`title` INT, `link` INT, `surface` INT, `image` INT, `price` INT, `date` INT);

-- -----------------------------------------------------
-- View `houses`.`houses`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `houses`.`houses`;
USE `houses`;
CREATE  OR REPLACE ALGORITHM=UNDEFINED DEFINER=`root`@`localhost` SQL SECURITY DEFINER VIEW `houses`.`houses` AS select `i`.`title` AS `title`,`i`.`link` AS `link`,`i`.`surface` AS `surface`,`i`.`image` AS `image`,`p`.`price` AS `price`,`p`.`date` AS `date` from (`houses`.`information` `i` join `houses`.`price` `p` on((`i`.`link` = `p`.`link`)));

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
